Repository DigiChanges/next-experience, pull requests merged in 2024-09, with the labels that each got.

#31 fix/mp/fixed-it-enough-so-it-can-build-successfully
  .gitignore
  pnpm-lock.yaml
  src/app/[locale]/auth/expired-link/page.tsx
  src/app/[locale]/auth/recovery-code/page.tsx
  src/app/[locale]/auth/welcome/page.tsx
  src/app/[locale]/profile/page.tsx
  src/app/not-found.tsx
  src/app/providers.tsx
  src/features/auth/expired-link/organisms/ExpiredLink.tsx
  src/features/auth/expired-link/template/ExpiredLinkTemplate.tsx
  src/features/auth/forgot-password/actions/forgotPasswordAction.ts
  src/features/auth/forgot-password/organisms/forgotPasswordForm.tsx
  src/features/auth/login/organisms/login/LoginForm.tsx
  src/features/auth/recovery-code/actions/recoveryCodeAction.ts
  src/features/auth/recovery-code/organisms/recoveryCode.tsx
  src/features/auth/update-password/actions/updatePasswordAction.ts
  src/features/auth/update-password/organisms/updatePasswordForm.tsx
  src/features/auth/welcome/organisms/authWelcome.tsx
  src/features/auth/welcome/template/AuthWelcomeTemplate.tsx
  src/features/items/atoms/addItem/AddItemBtn.tsx
  src/features/items/atoms/card/CardItem.tsx
  src/features/items/atoms/deleteItem/DeleteItemBtn.tsx
  src/features/items/atoms/editItem/EditItemBtn.tsx
  src/features/items/atoms/noItems/NoItemsToDisplay.tsx
  src/features/items/organisms/List.tsx
  src/features/items/template/update/UpdateItemTemplate.tsx
  src/features/navbar/atom/BurguerButton.tsx
  src/features/navbar/constants/dataNav.ts
  src/features/navbar/molecules/dropdown/DropdownUser.tsx
  src/features/navbar/organisms/Navbar.tsx
  src/features/profile/organisms/profile.tsx
  src/features/profile/template/ProfileTemplate.tsx
  src/features/setting/atoms/SwitchNotificationSettings/SwitchNotificationSettings.tsx
  src/features/setting/constants/dataSetting.ts
  src/features/setting/molecules/settingNotification/settingNotification.tsx
  src/features/setting/molecules/settingUpdatePassword/settingUpdatePassword.tsx
  src/features/shared/atoms/changeLenguage/changeLenguage.tsx
  src/features/shared/atoms/dropdown/Dropdown.tsx
  src/features/shared/atoms/filterModal/filterModal.module.css
  src/features/shared/atoms/filterModal/filterModal.tsx
  src/features/shared/atoms/inputForm/InputForm.tsx
  src/features/shared/atoms/inputForm/inputForm.module.css
  src/features/shared/atoms/modal/Modal.tsx
  src/features/shared/atoms/show/Show.tsx
  src/features/shared/atoms/sort/Sort.tsx
  src/features/shared/hooks/icons.ts
  src/features/shared/hooks/useFilter.ts
  src/features/shared/molecules/filtersApplied/FiltersApplied.tsx
  src/features/shared/molecules/inputSearchFromTo/InputSearchFromTo.tsx
  src/features/shared/molecules/inputSimple/InputSearchSimple.tsx
  src/features/shared/organisms/filterAndSearch/FilterAndSearch.tsx
  src/layout/private-layout/PrivateLayout.tsx
  tailwind.config.cjs
Labels: bug

#32 feat/imp/adding-error-page-to-reused-link - new invalid link page
  messages/en.json
  src/app/[locale]/auth/invalid-link/page.tsx
  src/app/error.tsx
  src/features/auth/invalid-link/organisms/InvalidLink.module.css
  src/features/auth/invalid-link/organisms/InvalidLink.tsx
  src/features/auth/invalid-link/template/InvalidLinkTemplate.tsx
  src/features/auth/update-password/organisms/updatePasswordForm.tsx
  src/features/items/template/ItemsTemplate.tsx
  src/features/shared/atoms/inputForm/InputForm.tsx
  src/features/shared/atoms/inputSearch/InputSearch.tsx
  src/features/shared/atoms/select/SelectForm.tsx
  src/features/shared/molecules/inputDynamic/InputDynamic.tsx
  src/features/shared/molecules/inputKeysFilter/inputKeysFilter.tsx
  src/features/shared/molecules/inputOptions/InputOptions.tsx
  src/features/shared/molecules/inputSearchFromTo/InputSearchFromTo.tsx
  src/features/shared/molecules/inputSimple/InputSearchSimple.tsx
  src/features/shared/molecules/inputSimple/inputSearchSimple.module.css
  src/features/shared/organisms/filterAndSearch/FilterAndSearch.tsx
Labels: enhancement

#36 fix/imp/inputs-refactor
  messages/en.json
  messages/es.json
  src/features/auth/forgot-password/organisms/forgotPasswordForm.tsx
  src/features/auth/login/organisms/login/LoginForm.tsx
  src/features/auth/recovery-code/organisms/recoveryCode.tsx
  src/features/auth/register/interfaces/IRegisterForm.ts
  src/features/auth/register/organisms/register/RegisterForm.tsx
  src/features/auth/register/validations/registerSchema.ts
  src/features/auth/update-password/organisms/updatePasswordForm.tsx
  src/features/items/organisms/formCreate/FormCreate.tsx
  src/features/items/organisms/formUpdate/FormUpdate.tsx
  src/features/setting/molecules/settingUpdatePassword/settingUpdatePassword.tsx
  src/features/shared/atoms/inputForm/InputForm.tsx
  src/features/shared/atoms/inputForm/inputFile/InputFile.tsx
  src/features/shared/atoms/inputForm/inputSelect/InputSelect.tsx
  src/features/shared/atoms/inputForm/inputSimple/InputSimple.tsx
Labels: bug, enhancement

#38 type attribute change to description
  messages/en.json
  messages/es.json
  src/features/items/constants/modalData.ts
  src/features/items/constants/selectOptionsData.ts
  src/features/items/interfaces/itemsResponse.ts
  src/features/items/models.ts
  src/features/items/organisms/List.tsx
  src/features/items/organisms/formCreate/FormCreate.tsx
  src/features/items/organisms/formUpdate/FormUpdate.tsx
  src/features/items/validations/modalSchema.ts
  src/features/navbar/organisms/Navbar.tsx
Labels: bug, enhancement

#40 features/shared/actions
  src/features/items/actions/ItemAction.ts
  src/features/items/organisms/formCreate/FormCreate.tsx
  src/features/shared/actions/config.ts
  src/features/shared/actions/fileAction.ts
Labels: enhancement

#39 feat/amh/profile
  .gitignore
  messages/en.json
  messages/es.json
  package-lock.json
  package.json
  src/asset/images/pencil.svg
  src/asset/images/user.webp
  src/features/auth/register/organisms/register/RegisterForm.tsx
  src/features/profile/actions/ProfileAction.ts
  src/features/profile/interfaces/profileResponse.ts
  src/features/profile/organisms/profile.module.css
  src/features/profile/organisms/profile.tsx
  src/features/profile/template/ProfileTemplate.tsx
  src/features/profile/validations/profileImageSchema.ts
  src/features/shared/actions/fileAction.ts
  src/features/shared/atoms/inputForm/InputForm.tsx
  src/features/shared/atoms/inputForm/inputFile/InputFile.tsx
  src/features/shared/atoms/inputForm/inputSelect/InputSelect.tsx
  src/features/shared/atoms/inputForm/inputSimple/InputSimple.tsx
  src/features/shared/hooks/icons.ts
  src/features/shared/hooks/images.ts
  src/service/HttpService.ts
  tailwind.config.cjs
Labels: enhancement
